### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by xneoron** [gsuitedevs/dotnet-samples#10]
![2](https://user-images.githubusercontent.com/20148261/49958717-35c5a280-ff3e-11e8-9912-460dc9f0f160.PNG)
![capture](https://user-images.githubusercontent.com/20148261/49958718-35c5a280-ff3e-11e8-972d-0efd37178e20.PNG)

what should i can do ? please help me !

**Comment by erickoledadevrel** [comment]
The Sheets API quickstart uses the readonly scope:

https://github.com/gsuitedevs/dotnet-samples/blob/master/sheets/SheetsQuickstart/SheetsQuickstart.cs#L32

If you want to start making create requests you need to get a new token with a more permissive scope:

https://developers.google.com/sheets/api/guides/authorizing#OAuth2Authorizing
