### ISSUE TITLE
Google Calendar Api working fine Locally but not raising its Authentication on Server

### ISSUE THREAD

**Issue by RushikPatel** [gsuitedevs/dotnet-samples#12]
I have created a project in console.developers.google.com to use Google Calendar API. there we need to generate credential and select application type

For Localhost and application type other following is the Json which works fine.

> {
>          "installed": {
>          "client_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com",
>          "project_id": "xxxxxx-00000",
>          "auth_uri": "https://accounts.google.com/o/oauth2/auth",
>          "token_uri": "https://accounts.google.com/o/oauth2/token",
>          "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
>          "client_secret": "xxxxxxxxxxxx",
>          "redirect_uris": [ "urn:ietf:wg:oauth:2.0:oob", "http://localhost" ]
>       }
>   }

And for Application type Web Application to Host on Server Few parameters has different Values in Json as shown below.

> {
>     "web": {
>     "client_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com",
>     "project_id": "xxxxxxxx-99999",
>     "auth_uri": "https://accounts.google.com/o/oauth2/auth",
>     "token_uri": "https://accounts.google.com/o/oauth2/token",
>     "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
>     "client_secret": "xxxxxxxxxxxxxxxxxxxxxxx",
>     "redirect_uris": [ "http://demo.mydemo.com" ],
>     "javascript_origins": [ "http://demo.mydemo.com" ]
>     }
> }

Can anyone help me to solve this issue?

Error is as follows

> System.AggregateException: One or more errors occurred. ---> System.NotSupportedException: Failed to launch browser with "https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&response_type=code&client_id=xxxxxxxxxxxx-vqi4faduqgcpt3d2ruv53ltgr0rkgfsb.apps.googleusercontent.com&redirect_uri=http:%2F%2Flocalhost:53998%2Fauthorize%2F&scope=https:%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar" for authorization. See inner exception for details. ---> System.ComponentModel.Win32Exception: Access is denied
>    at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
>    at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
>    at Google.Apis.Auth.OAuth2.LocalServerCodeReceiver.<ReceiveCodeAsync>d__8.MoveNext()
>    --- End of inner exception stack trace ---
>    at Google.Apis.Auth.OAuth2.LocalServerCodeReceiver.<ReceiveCodeAsync>d__8.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at Google.Apis.Auth.OAuth2.AuthorizationCodeInstalledApp.<AuthorizeAsync>d__8.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Google.Apis.Auth.OAuth2.GoogleWebAuthorizationBroker.<AuthorizeAsync>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Google.Apis.Auth.OAuth2.GoogleWebAuthorizationBroker.<AuthorizeAsync>d__1.MoveNext()
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
>    at KriyaCRM.Controllers.ActivitiesController.GetCalendarConnection(Activities objact, String Operation)
> ---> (Inner Exception #0) System.NotSupportedException: Failed to launch browser with "https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&response_type=code&client_id=430760523223-vqi4faduqgcpt3d2ruv53ltgr0rkgfsb.apps.googleusercontent.com&redirect_uri=http:%2F%2Flocalhost:53998%2Fauthorize%2F&scope=https:%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar" for authorization. See inner exception for details. ---> System.ComponentModel.Win32Exception: Access is denied
>    at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
>    at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
>    at Google.Apis.Auth.OAuth2.LocalServerCodeReceiver.<ReceiveCodeAsync>d__8.MoveNext()
>    --- End of inner exception stack trace ---
>    at Google.Apis.Auth.OAuth2.LocalServerCodeReceiver.<ReceiveCodeAsync>d__8.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at Google.Apis.Auth.OAuth2.AuthorizationCodeInstalledApp.<AuthorizeAsync>d__8.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Google.Apis.Auth.OAuth2.GoogleWebAuthorizationBroker.<AuthorizeAsync>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Google.Apis.Auth.OAuth2.GoogleWebAuthorizationBroker.<AuthorizeAsync>d__1.MoveNext()<---
> --> Important Link related to API : https://www.codeproject.com/Articles/1183150/Securing-ASP-NET-Web-API-using-Custom-Token-Based <--

**Comment by RushikPatel** [comment]
Hello Steve,

Thank's for reply this question.
I am currently use C# .net technology web project and using google calendar api integration in this web project. but this error raise in live server site. 

> System.AggregateException: One or more errors occurred. ---> System.NotSupportedException: Failed to launch browser with "https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&response_type=code&client_id=xxxxxxxxxxxx-vqi4faduqgcpt3d2ruv53ltgr0rkgfsb.apps.googleusercontent.com&redirect_uri=http:%2F%2Flocalhost:53998%2Fauthorize%2F&scope=https:%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar" for authorization. See inner exception for details. ---> System.ComponentModel.Win32Exception: Access is denied

But Locally in localhost is working fine.

Thank you,
Rushik Patel

**Comment by RushikPatel** [comment]
Hello,

Can you please give me proper solution and any idea ?

**Comment by erickoledadevrel** [comment]
The quickstart in this repo is designed to work on the command line only. To perform the authorization flow in a web application you must use a different set of authorization code:

https://developers.google.com/api-client-library/dotnet/guide/aaa_oauth
