### ISSUE TITLE
credential return null

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [gsuitedevs/dotnet-samples#15]
I have read client_secrect.json and return Stream is OK. 
But untill credentiall is null
`credential = await GoogleWebAuthorizationBroker.AuthorizeAsync(
                GoogleClientSecrets.Load(streamFile).Secrets,
                Scopes, "user", 
                CancellationToken.None,null);`

**Comment by erickoledadevrel** [comment]
The sample expects the client secrets to be in a file called `credentials.json`.

**Comment by nguyenthanhliemfc** [comment]
@erickoledadevrel Thank you for your reply!
Next I get this error One or more errors occurred. (Failed to launch browser with **"https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&response_type=code&client_id**

**Comment by erickoledadevrel** [comment]
Looks similar to #14. Please follow that issue.
