### ISSUE TITLE
Error when creating credentials.json on Enable API Click

### ISSUE THREAD

**Issue by rodneyjoyce** [gsuitedevs/dotnet-samples#16]
The docs here https://developers.google.com/admin-sdk/reports/v1/quickstart/dotnet say click on "Enable The Reports API" and in a resulting diaglog you can download the Client Confioguration and save it as credentials.json.

When I click on the button it says "Something went wrong. Please try again." with no further information (chomre tools don't show anything extra). The API is enabled already and I have credentials for it. I don't know the schema of the credentials.json file so not sure what to do next.

I don't have another Gsuite account so unable to test in another account.

See screenshot:
https://www.screencast.com/t/UxhrdyBbm5j

**Comment by erickoledadevrel** [comment]
Sorry for the trouble, not sure what's going on there. Is it still happening on your account? I'm not able to reproduce the problem on my own account.

**Comment by rodneyjoyce** [comment]
No problem - it seems to have resolved itself... we'll just put it down to a one-off...
