### ISSUE TITLE
Unable to find pacakge 'Google.Apis.Services'  and 'Google.Apis.Utils'

### ISSUE THREAD

**Issue by TheBossBaby** [gsuitedevs/dotnet-samples#18]
## Expected Behavior

Find and Install mentioned packages by NuGet

## Actual Behavior

Can't find the mentioned packages by NuGet

## Specifications

  - OS Linux

**Comment by erickoledadevrel** [comment]
Those class paths aren't NuGet packages, they are included in other packages. I'm not sure which quickstart you are running, but it doesn't advise you to install them directly. For example, for the Calendar API quickstart you only install `Google.Apis.Calendar.v3` and it will find all of the dependencies.
