### ISSUE TITLE
URL changes every time you run the application

### ISSUE THREAD

**Issue by blakecodes** [gsuitedevs/dotnet-samples#21]
Every time I run the console application, the port on the URL that is accessing the Google OAuth page changes. 

I get the following error:

> The redirect URI in the request, http://127.0.0.1:58639/authorize/, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs

How can I keep the port consistent every time I run the app?

https://github.com/gsuitedevs/dotnet-samples/blob/99495d6139451f5b7deb92e237b715986787352e/drive/activity-v2/DriveActivityQuickstart/DriveActivityQuickstart.cs#L45

**Comment by erickoledadevrel** [comment]
If you create an OAuth client ID of type "Other", which the button in the quickstart will do automatically, then all ports on localhost are allowed.

**Comment by blakecodes** [comment]
@erickoledadevrel thanks for the insight.
