### ISSUE TITLE
Google CalendarException

### ISSUE THREAD

**Issue by sirsbusiso** [gsuitedevs/dotnet-samples#22]
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)

**Comment by erickoledadevrel** [comment]
Unfortunately you didn't provide enough information to allow us to debug the issue.

**Comment by sirsbusiso** [comment]
Hi there,

I was trying to test the Calendar api on my console application and the exception I encounter says 'System.IO.FileNotFoundException: Could not find file' for the credentials.json file that I downloaded and added onto my project.

Thanks.
[CalendarIssue.docx](https://github.com/gsuitedevs/dotnet-samples/files/3501585/CalendarIssue.docx)

**Comment by erickoledadevrel** [comment]
Please ensure you have followed the directions in the quickstart:

https://developers.google.com/calendar/quickstart/dotnet#step_3_set_up_the_sample

**Comment by sirsbusiso** [comment]
I will do so, thanks Erick.

**Comment by sirsbusiso** [comment]
Hi Erick,

I have tried following the step by step tutorial and I encounter an Auth exception, please see below.

Unhandled Exception: System.InvalidOperationException: At least one client secrets (Installed or Web) should be set at Google.Apis.Auth.OAuth2.GoogleClientSecrets.get_Secrets() at ConsoleApplication1.Program.Main(String[] args)
