### ISSUE TITLE
Request payload size exceeds the limit: 10485760 bytes.

### ISSUE THREAD

**Issue by thsures** [gsuitedevs/dotnet-samples#23]
(Please search [existing issues](https://github.com/gsuitedevs/dotnet-samples/issues) before creating a new one.)

**Sample Name:**

## Expected Behavior
It should upload number of records irrespective of the count.

## Actual Behavior
after the records count increases it showing the error.

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - .NET version:
  - OS (Mac/Linux/Windows):

**Comment by erickoledadevrel** [comment]
This appears to be an issue with custom code you have written, not a sample in this repo. The API infrastructure does have a size limit for a single request. If you exceed that limit, break your work into multiple requests.

**Comment by thsures** [comment]
As you said if the API Infrastructure has some limit can you please provide the size limit and if possible can you please help me to break into multiple request.

**Comment by erickoledadevrel** [comment]
I don't believe the limit is publicly documented, and is subject to change. Please see the API's support page for more information on how to get support.

**Comment by thsures** [comment]
Thank you sir.
