### ISSUE TITLE
System.AggregateException

### ISSUE THREAD

**Issue by lucianodekno** [gsuitedevs/dotnet-samples#3]
(Please search [existing issues](https://github.com/gsuitedevs/dotnet-samples/issues) before creating a new one.)

**Sample Name:**

.NET Quickstart
## Expected Behavior
Run the example

## Actual Behavior
System.AggregateException: 
-HttpRequestException: An error occurred while sending the request.
-WebException: Error en el servidor remoto: (407) Se requiere autenticación del proxy.
This happens in line 31 ("credential = GoogleWebAuthorizationBroker.AuthorizeAsync(...")

## Steps to Reproduce the Problem

https://developers.google.com/gmail/api/quickstart/dotnet

## Specifications

  - .NET version: 4.6.1
  - OS (Mac/Linux/Windows): Windows

**Comment by grant** [comment]
The error 407 suggests there is a proxy in use for the internet connection. Are you able to run the quickstart without a proxy?

**Comment by grant** [comment]
Hi @lucianodekno, were you able to run the quickstart without a proxy?
