### ISSUE TITLE
Google API

### ISSUE THREAD

**Issue by sarahhassan01** [gsuitedevs/dotnet-samples#4]
using Google.Apis.Auth.OAuth2;
this and which such it, doesn't work for me!?
how can i add library to it to make it work???
note*
i already have Nuget.org Library in my Visual Studio

**Comment by erickoledadevrel** [comment]
Unfortunately you didn't provide enough information for us to be able to help you.

**Comment by sarahhassan01** [comment]
no problem i solved it already
