### ISSUE TITLE
Default Application Name not working

### ISSUE THREAD

**Issue by jmroyb** [gsuitedevs/dotnet-samples#5]
**Sample Name: VPA**

## Expected Behavior: 
Show VPA application name in Sign In broser page

## Actual Behavior: 
Showing Quickstart application name

## Steps to Reproduce the Problem
  Execute https://developers.google.com/calendar/quickstart/dotnet code as is

## Specifications
  - Browsers: Edge (from Win10 v10.0.17134.286), Firefox 62 
  - .NET version: 4.7
  - OS (Mac/Linux/Windows): Windows

![2a](https://user-images.githubusercontent.com/4932314/46249388-71ad9900-c420-11e8-94e8-e50a49ba7ae4.png)

![2b](https://user-images.githubusercontent.com/4932314/46249390-770ae380-c420-11e8-9de6-45386d2f1886.png)

![2c](https://user-images.githubusercontent.com/4932314/46249416-e54fa600-c420-11e8-88f3-58e18f2c8287.png)

**Comment by erickoledadevrel** [comment]
The `ApplicationName` set in your code is only used for logging and other internal purposes. The name that appears in the OAuth approval dialog is set in the Cloud Console project you created, under **APIs & Services -> Credentials -> OAuth Consent Screen**:

https://console.cloud.google.com/apis/credentials/consent

**Comment by jmroyb** [comment]
Thanks for updating
