### ISSUE TITLE
GoogleWebAuthorizationBroker.AuthorizeAsync(...).Result blocked indefinitely

### ISSUE THREAD

**Issue by jmroyb** [gsuitedevs/dotnet-samples#6]
## Expected Behavior:
Raise an exception or continue execution when browser or tab browser is closed without typing Sign In credentials

## Actual Behavior: 
GoogleWebAuthorizationBroker.AuthorizeAsync(...).Result is blocked indefinitely

## Steps to Reproduce the Problem
     1. Execute https://developers.google.com/calendar/quickstart/dotnet code as is.
     2. When Sign In page appears, close tab. Code remains blocked
     3. When Sign In page appears, close browser. Code remains blocked
 
## Specifications
  - Browsers: Edge (from Win10 v10.0.17134.286), Firefox 62 
  - .NET version: 4.7
  - OS (Mac/Linux/Windows): Windows

**Comment by erickoledadevrel** [comment]
I believe this same issue was discussed here:

https://github.com/googleapis/google-api-dotnet-client/issues/508#issuecomment-290700919

Please continue the discussion there, as the functionality of the .NET library is outside the scope of this samples repo.
