### ISSUE TITLE
After valid Sign In browser tab remains opened

### ISSUE THREAD

**Issue by jmroyb** [gsuitedevs/dotnet-samples#7]
## Expected Behavior:
After a valid Sign In, tab browser or browser it self should be closed. If Api opens a tab, Api should close it or provide another mechanism for Sig In not based on browser

## Actual Behavior
After a valid Sign In tab browser or browser it self is not closed and a ugly text appears (see attachment)

## Steps to Reproduce the Problem

  1. Execute https://developers.google.com/calendar/quickstart/dotnet code as is.
  2. Write a valid user name  and password in Sign In page 

## Specifications

    Browsers: Edge (from Win10 v10.0.17134.286), Firefox 62
    .NET version: 4.7
    OS (Mac/Linux/Windows): Windows

![3](https://user-images.githubusercontent.com/4932314/46250165-f1416500-c42c-11e8-8f89-76caa01dbffb.png)

**Comment by erickoledadevrel** [comment]
This is the behavior of the Google APIs .NET Client Library. If you'd like to see a change in that library, please file an issue here:

https://github.com/googleapis/google-api-dotnet-client

In general my understanding is that web browsers have restrictions on when pages are allowed to close themselves that prevent it in this case where the browser is launched from the command line.

**Comment by xavierfoucrier** [comment]
Hi @erickoledadevrel,

Do you know if it is possible to change this behavior, for example redirect the user to a **custom webpage** on the net?

Thanks :wink:
